
POINTS <- read.csv('points.txt', header = FALSE)
POINTS@names = c('No', 'X coord', 'Y coord')

P_NOF_POINTS <- nrow(POINTS)
P_NOF_GENERATIONS <- 10000
P_GENERATION_SIZE <- 1000
P_NOF_INSTANCES_TO_KEEP <- 10
P_NOF_MUTATIONS_TO_GENERATE <- (P_GENERATION_SIZE - P_NOF_INSTANCES_TO_KEEP) / P_NOF_INSTANCES_TO_KEEP

DISTANCES <- matrix(nrow = P_NOF_POINTS, ncol = P_NOF_POINTS)
for (I in 1:(P_NOF_POINTS - 1))
	for (J in (I + 1):P_NOF_POINTS) {
		DIST_X <- POINTS[I, 2] - POINTS[J, 2]
		DIST_Y <- POINTS[I, 3] - POINTS[J, 3]
		DISTANCES[I, J] <- sqrt(DIST_X * DIST_X + DIST_Y * DIST_Y)
	}

GENERATE_ROUTE <- function() {
	sample(1:P_NOF_POINTS, P_NOF_POINTS)
}

MUTATE_ROUTE <- function(ROUTE) {
	POSITIONS <- sample(1:P_NOF_POINTS, 2)
	TMP <- ROUTE[POSITIONS[1]]
	ROUTE[POSITIONS[1]] <- ROUTE[POSITIONS[2]]
	ROUTE[POSITIONS[2]] <- TMP
	ROUTE
}

CALCULATE_DISTANCE <- function(ROUTE) {
	DISTANCE <- 0
	for (I in 1:P_NOF_POINTS) {
		POINT_1 <- if (I == 1) ROUTE[P_NOF_POINTS] else ROUTE[I - 1]
		POINT_2 <- ROUTE[I]
		DISTANCE <- DISTANCE + DISTANCES[min(POINT_1, POINT_2), max(POINT_1, POINT_2)]
	}
	DISTANCE
}

GENERATION <- matrix(nrow = P_GENERATION_SIZE, ncol = P_NOF_POINTS + 1)
for (I in 1:P_GENERATION_SIZE) {
	ROUTE <- GENERATE_ROUTE()
	GENERATION[I,] <- c(ROUTE, CALCULATE_DISTANCE(ROUTE))
}

for (I in 1:P_NOF_GENERATIONS) {
	print(I)

	ORDER <- order(GENERATION[, P_NOF_POINTS + 1])
	GENERATION <- GENERATION[ORDER,]


	for (J in 1:P_NOF_INSTANCES_TO_KEEP)
		for (K in 1:P_NOF_MUTATIONS_TO_GENERATE) {
			L <- P_NOF_INSTANCES_TO_KEEP + (J - 1) * P_NOF_MUTATIONS_TO_GENERATE + K
			ROUTE <- MUTATE_ROUTE(GENERATION[J, 1:P_NOF_POINTS])
			GENERATION[L,] <- c(ROUTE, CALCULATE_DISTANCE(ROUTE))
		}
}
